name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Tests (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install dependencies
        run: uv sync --locked --group test
      - if: matrix.python-version == '3.13'
        name: Run tests (with coverage)
        run: uv run pytest --cov=slotscheck
      - if: matrix.python-version != '3.13'
        name: Run tests
        run: uv run pytest

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install dependencies
        run: uv sync --locked --group test --group typecheck
      - name: Run type checks
        run: uv run mypy --pretty src tests/src

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
      - name: check lockfile
        run: uv lock --check
      - name: Install dependencies
        run: uv sync --locked --group linting
      - name: Run linters
        run: |
          uv run ruff format --check .
          uv run ruff check .
          uv run slotscheck -m slotscheck --verbose

  # https://github.com/marketplace/actions/alls-green#why
  all-green:
    name: Are all checks green?
    if: always()
    needs:
      - test
      - typecheck
      - lint
    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  check-tag:
    name: Check tag correctness
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - uses: actions/checkout@v6
      - run: |
          version=$(grep -E '^version\s*=' pyproject.toml | sed -E 's/^version\s*=\s*"([^"]+)".*/\1/')

          tag="${GITHUB_REF_NAME}"

          echo "Detected version in pyproject.toml: $version"
          echo "Detected tag name: $tag"

          # Compare them
          if [ "v$version" != "$tag" ]; then
            echo "❌ Tag ($tag) does not match version in pyproject.toml ($version)"
            exit 1
          fi

          echo "✅ Tag matches version. Proceeding with release..."

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: [all-green, check-tag]
    environment: PyPI
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
      - run: uv build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
